status = [
  # Buildkite: osx/linux installers
  "buildkite/klarity",

  # Hydra: we just care about tests attribute set
  "ci/hydra:Bcc:klarity:tests.runFlow",
  "ci/hydra:Bcc:klarity:tests.runLint",
  "ci/hydra:Bcc:klarity:tests.runShellcheck"
]
timeout_sec = 7200
required_approvals = 1
cut_body_after = "## Type of change"
delete_merged_branches = true
block_labels = [ "DO NOT MERGE", "WIP" ]
